name: 构建镜像并推送

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - name: 签出仓库
      uses: actions/checkout@v3
         
    - name: 登录DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: 制作镜像并上传
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.IMAGE }}
        build-args: |
          PORT: ${{ secrets.PORT || 80 }}
          USERNAME=${{ secrets.USERNAME }}
          PASSWORD=${{ secrets.PASSWORD }}
          UUID=${{ vars.UUID }}
          PATH_VLESS=${{ secrets.PATH_VLESS }}
          PATH_VMESS=${{ secrets.PATH_VMESS }}
          WARP_SERVER=${{ secrets.WARP_SERVER }}
          WARP_KEY=${{ secrets.WARP_KEY }}
          TUNNEL=${{ secrets.TUNNEL }}
